[package]
name = "ru_audio_spectrum"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.1.8", features = ["derive"] }
num-complex = "0.4.3"
plotters = "0.3.4"
wav = "1.0.0"
